<?xml version="1.0"?>
<robot name="follower" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.6"/>
    <xacro:property name="base_width" value="0.4"/>
    <xacro:property name="base_height" value="0.1"/>
    <xacro:property name="wheel_length" value="0.1"/>
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="caster_radius" value="0.05"/>
    <xacro:property name="cam_radius" value="0.02"/>
    
    <material name="green">
        <color rgba="0.0 0.8 0.0 0.9"/>
    </material>

    <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
    </material>

    <material name="gray">
        <color rgba="0.5 0.5 0.5 0.8"/>
    </material>

    <link name="ground"/>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="green"/>
        </visual>

        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </collision>
        <xacro:box_inertia m="1.0" l="${base_length}" w="${base_width}" h="${base_height}"
                           xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
    </link>

    <joint name="base_ground" type="fixed">
        <parent link="ground"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 0.1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="1.5707 0.0 0.0"/>
            <material name="black"/>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="1.5707 0.0 0.0"/>
        </collision>
        <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_length}" 
                            xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
    </link>

    <joint name="left_base" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="${-base_length/3.0} ${base_width / 2.0 + wheel_length / 2.0} 0.0" rpy="0.0 0.0 0.0"/>
        <axis xyz="0.0 1.0 0.0"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="1.5707 0.0 0.0"/>
            <material name="black"/>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="1.5707 0.0 0.0"/>
        </collision>
        <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_length}" 
                            xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
    </link>

    <joint name="right_base" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="${-(base_length/3.0)} ${-(base_width / 2.0 + wheel_length / 2.0)} 0.0" rpy="0.0 0.0 0.0"/>
        <axis xyz="0.0 1.0 0.0"/>
    </joint>

    <link name="caster">
        <visual>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <material name="gray"/>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
        </collision>
        <xacro:sphere_inertia m="0.1" r="${caster_radius}"
                            xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="caster_joint" type="continuous">
        <parent link="base_link"/>
        <child link="caster"/>
        <origin xyz="0.2 0.0 -0.05"/>
        <axis xyz="1.0 0.0 0.0"/>
    </joint>

    <link name="camera_link">
        <visual>
            <geometry>
                <sphere radius="${cam_radius}"/>
            </geometry>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${cam_radius}"/>
            </geometry>
        </collision>
        <xacro:sphere_inertia m="0.1" r="${cam_radius}"
                            xyz="0 0 0" rpy="0 0 0"/>
    </link>

    <joint name="camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link"/>
        <origin xyz="${base_length/2.0} 0.0 ${base_height/2.0 + cam_radius}" rpy="0.0 0.34 0.0"/>
    </joint>

</robot>